env:
  - GO111MODULE=on

before:
  hooks:
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X "main.Version={{.Version}}"
      - -X "main.Commit={{.FullCommit}}"
      - -X "main.RepoUrl={{.GitURL}}"
      - -X "main.BuildDate={{.Date}}"
      - -X "main.BuiltWithGoVersion={{.Env.GOLANG_VERSION}}"
      - -X "main.BuiltBy={{.Env.BUILT_BY}}"
    flags:
      - -tags=release
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - format: gz
    files:
      - none*
    replacements:
      darwin: mac
    format_overrides:
      - goos: windows
        format: zip
