name: goreleaser

on:
  # release:
  #   types: published
  # push:
  #   branches:
  #     - master
  # schedule:
  #  - cron: 0 8 * * 5
  watch:
   types: started

env:
  UPXVER: 3.94

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install upx
        run: |
          echo "Installing upx .."
          curl -OL "https://github.com/upx/upx/releases/download/v${UPXVER}/upx-${UPXVER}-amd64_linux.tar.xz"
          tar xvf "upx-${UPXVER}-amd64_linux.tar.xz"
          cp "upx-${UPXVER}-amd64_linux/upx" "$(go env GOPATH)/bin"
          ls -al "$(go env GOPATH)/bin"
          upx --version
          chmod +x upx.sh
          ls -al
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --skip-validate --skip-sign --debug
        env:
          GO_VERSION: $(go version)
          BUILT_BY: $(whoami)@$(hostname)
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
